version: '3.9'

services:
  # Database
  db:
    # POSTGRESQL CONTAINER
    image: 'postgres:latest'
    container_name: local_pgdb
    restart: 'no'
    ports:
      - '5678:5432'
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   restart: always
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   depends_on:
  #     - db 
  #   links: 
  #     - db 

    # MONGO CONTAINER ------------
    # image: mongo
    # container_name: db
    # restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: password
    #   # Create a new database. Please note, the
    #   # /docker-entrypoint-initdb.d/init.js has to be executed
    #   # in order for the database to be created
    #   MONGO_INITDB_DATABASE: site
    # volumes:
    #   - ./db-init.js:/docker-entrypoint-initdb.d/db-init.js:ro
    #   - ./mongo-volume:/data/db
    # ports:
    #   - '27017-27019:27017-27019'
    
  #client
  client:
    build: client/.
    image: client-app
    ports:
      - 80:80
    restart: always
    environment:
      # Use the username and password found in the db-init.js file instead
      # of the root username.
      MONGODB_URI: mongodb://user:secretPassword@database/site
    volumes: 
      - ./client/:/dist/src/app/ 
      - ./certbot/www:/var/www/certbot:ro
      - ./client/nginx.conf:/etc/nginx/conf.d:ro
    networks:
      - site
  #server
  server:
    build: server/.
    image: server-app
    command: npm run start:dev
    user: root
    depends_on:
      - db
    ports:
      - 3000:3000
    restart: unless-stopped
    # environment:
    #   # Use the username and password found in the db-init.js file instead
    #   # of the root username.
    #   MONGODB_URI: mongodb://user:secretPassword@database/site
    networks:
      - site
  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email paz.jorge1@gmail.com --agree-tos --no-eff-email -d jorgepaz.cl -d www.jorgepaz.cl
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
networks:
  site:
volumes:
  local_pgdata:
  pgadmin-data: